### ISSUE TITLE
How to support two USB-HOST ports?

### ISSUE THREAD

**Issue by qq8322302** [sekigon-gonnoc/Pico-PIO-USB#151]
"RP2040, I want to use 4 GPIO pins to simulate two USB-HOSTs, one for connecting a keyboard and one for connecting a mouse."
"Does this project support this? I couldn't find any relevant methods in the code."
"I used a USB-HUB for expansion, but I found that support for some USB-HUB chips is not good. The SL2.1A cannot recognize any connected devices, and the HS8836A cannot properly disconnect and reconnect the second device."

**Comment by No0ne** [comment]
You can use this function for that:
```c
int pio_usb_host_add_port(uint8_t pin_dp, PIO_USB_PINOUT pinout);
```

**Comment by qq8322302** [comment]
@No0ne  Thank you very much for your reminder. After testing, it has been found that using pio_usb_ host _ ad_port can support multiple host ports.

**Comment by qq8322302** [comment]
@No0ne  Hi
May I ask if it is possible to support multiple ports in USB device mode? 
For example, port A is connected to PC1, port B is connected to PC2, and port C is connected to PC3.

**Comment by No0ne** [comment]
I was asking that here: https://github.com/sekigon-gonnoc/Pico-PIO-USB/issues/114
I don't think its possible at the momtent.

**Comment by qq8322302** [comment]
@No0ne  thank you very much for your help.

**Comment by kbladewht** [comment]
> [@No0ne](https://github.com/No0ne) Thank you very much for your reminder. After testing, it has been found that using pio_usb_ host _ ad_port can support multiple host ports.

Hi Sir, I used this code, but seems like it will stuck on the second host usb when I plug them together ?

**Comment by qq8322302** [comment]
> > [@No0ne](https://github.com/No0ne) Thank you very much for your reminder. After testing, it has been found that using pio_usb_ host _ ad_port can support multiple host ports.
> 
> Hi Sir, I used this code, but seems like it will stuck on the second host usb when I plug them together ?

Here, I'm conducting the test using the keyboard and mouse. Both of the two ports are functioning properly.

**Comment by No0ne** [comment]
Yes two **host** ports work fine but in https://github.com/sekigon-gonnoc/Pico-PIO-USB/issues/114 I was asking about two **device** ports.

**Comment by qq8322302** [comment]
Multiple device ports. Currently, it seems that they are not supported. We are looking forward to their support in the future.

**Comment by kbladewht** [comment]
> > > [@No0ne](https://github.com/No0ne) Thank you very much for your reminder. After testing, it has been found that using pio_usb_ host _ ad_port can support multiple host ports.
> > 
> > 
> > Hi Sir, I used this code, but seems like it will stuck on the second host usb when I plug them together ?
> 
> Here, I'm conducting the test using the keyboard and mouse. Both of the two ports are functioning properly.

thanks your confirm, it is weird, not sure how to orgnize codes other this one line
