### ISSUE TITLE
💡[FEATURE] Please support high pins on RP2350B

### ISSUE THREAD

**Issue by jepler** [sekigon-gonnoc/Pico-PIO-USB#156]
The RP2350B adds GPIO pins up to 47. Certain changes are needed to work with the "upper pins", such as using pio_claim_free_sm_and_add_program_for_gpio_range to correctly configure the PIO peripheral and pio_sm_set_{pin,pindirs}_with_mask64 to set the initial state of GPIO pins.

**Comment by jepler** [comment]
(ping @ladyada)

**Comment by arturo182** [comment]
Related: #133

**Comment by jepler** [comment]
thanks, missed it -- closing as duplicate
