### ISSUE TITLE
libusb possible?

### ISSUE THREAD

**Issue by brandonros** [sekigon-gonnoc/Pico-PIO-USB#2]
I'd love to be able to control a USB 2.0 device (not keyboard/mouse/HID) with RP2040. Is that possible with this project?

**Comment by sekigon-gonnoc** [comment]
Current version library exposes only interrupt transfer as an API.  If the device use only interrupt transfer, it may be possible to control it.

**Comment by brandonros** [comment]
What would need to be exposed other than interrupt transfers?

**Comment by sekigon-gonnoc** [comment]
Reading USB specifications and implement
